services:
- type: web
  name: next-js
  runtime: node
  plan: starter
  buildCommand: yarn; yarn build
  startCommand: yarn start
  autoDeploy: false
  pullRequestPreviewsEnabled: true 
  envVars:
  - key: NODE_ENV
    value: production
  - key: NEW_NAME_POST_LIZHIFAN_LEAVING_TEAMz_BAI
    value: test
  - key: TEST_TEST
    value: test
  - key: TEST_TEST_TEST
    value: meowowowwwow
# Uncomment the following to deploy this app as a static site on render
# - type: web
#   name: nextjs-static
#   runtime: static
#   buildCommand: yarn; yarn build
#   staticPublishPath: out
#   pullRequestPreviewsEnabled: true     # optional
#   envVars:
#   - key: NODE_ENV
#     value: production

